-- Keeper - Seed Data
-- Reseed-safe: clears all app data and reinserts a deterministic set of rows.
-- Safe to re-run at any time; TRUNCATE ... CASCADE removes dependent rows first.
-- To reseed: psql -U postgres -d ab2 -f db/seed.sql

TRUNCATE TABLE user_settings, calendar_events, connections, goals, users RESTART IDENTITY CASCADE;

-- =============================================================================
-- Users
-- One default profile is created for development and demo purposes.
-- Dev credentials: username `default_user`, password `keeper123`
-- The password_hash was generated by hashPassword() in backend/auth/passwords.js
-- using scrypt (N=16384, r=8, p=1). Do not commit real user passwords here.
-- =============================================================================
INSERT INTO users (id, username, name, pin, password_hash, must_reset_password, avatar) VALUES
(‘u1’, ‘default_user’, ‘Default User’, NULL, ‘scrypt$16384$8$1$afc5ab0471b03708469ce2271726c4ca$3c3cbf9d5b558466a9553beee14dae16ceed64547cb868ee24c30e145ae96dd39de9fe289d98f9d3e27ecbcf404d60c830024fadda1b1829be7b7fa4877b8f2d’, FALSE, ‘👨’);

-- =============================================================================
-- User settings
-- Each user gets a corresponding row in user_settings on creation.
-- Defaults: light theme, English language.
-- =============================================================================
INSERT INTO user_settings (id, user_id, theme, language) VALUES
(‘us1’, ‘u1’, ‘light’, ‘en’);

-- =============================================================================
-- Connections (all belong to u1)
-- Demonstrates a realistic mix of:
--   - relationship types: ‘friend’ and ‘connection’
--   - liked flag: true for people the user is actively investing in romantically
--   - milestones: JSONB tracking dates count, physical milestones, and contact streak
-- Dates use CURRENT_DATE intervals so the data stays relevant on any reseed date.
-- =============================================================================
INSERT INTO connections (id, user_id, name, age, phone, location, notes, gender, relationship, liked, created_at, milestones) VALUES
-- Friends (liked = false): milestone UI and RizzBot coaching are not shown for these.
(‘1’, ‘u1’, ‘David Lopez’, 24, ‘801-555-0101’, ‘Provo, UT’, ‘Met at BYU intramurals.’, ‘male’, ‘friend’, false, (CURRENT_DATE - INTERVAL ‘120 days’)::date, ‘{"dates":1,"heldHands":false,"kissed":false,"metParents":false,"contactStreak":3}’),
(‘3’, ‘u1’, ‘Noah Martinez’, 25, ‘801-555-0103’, ‘Lehi, UT’, ‘Gym buddy from VASA in Orem.’, ‘male’, ‘friend’, false, (CURRENT_DATE - INTERVAL ‘95 days’)::date, ‘{"dates":0,"heldHands":false,"kissed":false,"metParents":false,"contactStreak":4}’),
(‘5’, ‘u1’, ‘Ethan Kim’, 26, ‘801-555-0105’, ‘American Fork, UT’, ‘Works nearby and likes hiking.’, ‘male’, ‘friend’, false, (CURRENT_DATE - INTERVAL ‘60 days’)::date, ‘{"dates":0,"heldHands":false,"kissed":false,"metParents":false,"contactStreak":2}’),
-- Liked connections (liked = true): full milestone UI and RizzBot hints are enabled.
(‘2’, ‘u1’, ‘Emma Jensen’, 23, ‘801-555-0102’, ‘Orem, UT’, ‘Great conversations and very thoughtful.’, ‘female’, ‘connection’, true, (CURRENT_DATE - INTERVAL ‘150 days’)::date, ‘{"dates":6,"heldHands":true,"kissed":true,"metParents":false,"contactStreak":10}’),
(‘4’, ‘u1’, ‘Sophia Clark’, 22, ‘801-555-0104’, ‘Pleasant Grove, UT’, ‘Met at UVU student event.’, ‘female’, ‘connection’, true, (CURRENT_DATE - INTERVAL ‘70 days’)::date, ‘{"dates":3,"heldHands":true,"kissed":false,"metParents":false,"contactStreak":6}’),
(‘6’, ‘u1’, ‘Olivia Reed’, 24, ‘801-555-0106’, ‘Spanish Fork, UT’, ‘Met through a mutual friend in Provo.’, ‘female’, ‘connection’, true, (CURRENT_DATE - INTERVAL ‘45 days’)::date, ‘{"dates":2,"heldHands":false,"kissed":false,"metParents":false,"contactStreak":5}’);

-- =============================================================================
-- Calendar events (all belong to u1)
-- Spread across past, present, and future relative to CURRENT_DATE so the
-- calendar always has content regardless of when the seed is applied.
-- Event types: ‘date’, ‘hangout’, ‘call’, ‘text’, ‘other’
-- All events start as status=’planned’ with no outcome reported.
-- Note: events in the past (negative intervals) will show as needing a report
-- in the UI until the user logs in and marks them as happened/fell_through.
-- =============================================================================
INSERT INTO calendar_events (id, user_id, title, date, time, location, notes, type, connection_id, color, status, reported_at, report_notes, report_milestones) VALUES
-- Past events (will show as unreported in the UI)
(‘1’,  ‘u1’, ‘Brunch with Emma’,                    (CURRENT_DATE - INTERVAL ‘1 day’)::date,  ‘10:00’, ‘The Coffee Pod, Provo, UT’,                  ‘Recap last week and plan next date.’,                 ‘date’,    ‘2’, ‘#ec4899’, ‘planned’, NULL, NULL, NULL),
-- Today’s events
(‘2’,  ‘u1’, ‘Lunch with David’,                    CURRENT_DATE,                                ‘12:15’, ‘Station 22 Cafe, Provo, UT’,                 ‘Catch up on work and weekend plans.’,                 ‘hangout’, ‘1’, ‘#3b82f6’, ‘planned’, NULL, NULL, NULL),
(‘16’, ‘u1’, ‘Study block at library’,              CURRENT_DATE,                                ‘15:00’, ‘Orem Public Library, Orem, UT’,              ‘Two focused hours for school.’,                       ‘other’,   NULL, ‘#94a3b8’, ‘planned’, NULL, NULL, NULL),
-- Upcoming events (positive intervals)
(‘3’,  ‘u1’, ‘Gym session with Noah’,               (CURRENT_DATE + INTERVAL ‘1 day’)::date,    ‘18:00’, ‘VASA Fitness, Orem, UT’,                     ‘Leg day and post-workout smoothie.’,                  ‘hangout’, ‘3’, ‘#22c55e’, ‘planned’, NULL, NULL, NULL),
(‘17’, ‘u1’, ‘Call mom’,                            (CURRENT_DATE + INTERVAL ‘1 day’)::date,    ‘21:00’, ‘Provo, UT’,                                  ‘Weekly family check-in.’,                             ‘call’,    NULL, ‘#64748b’, ‘planned’, NULL, NULL, NULL),
(‘4’,  ‘u1’, ‘Ice cream walk with Sophia’,          (CURRENT_DATE + INTERVAL ‘2 days’)::date,   ‘19:00’, ‘Jakes Brookside, Springville, UT’,           ‘Walk around downtown after dessert.’,                 ‘date’,    ‘4’, ‘#f97316’, ‘planned’, NULL, NULL, NULL),
(‘5’,  ‘u1’, ‘Call Ethan about hiking route’,       (CURRENT_DATE + INTERVAL ‘2 days’)::date,   ‘20:30’, ‘American Fork, UT’,                          ‘Finalize trail and carpool details.’,                 ‘call’,    ‘5’, ‘#8b5cf6’, ‘planned’, NULL, NULL, NULL),
(‘6’,  ‘u1’, ‘Dinner with Olivia’,                  (CURRENT_DATE + INTERVAL ‘3 days’)::date,   ‘19:30’, ‘Communal, Provo, UT’,                        ‘Try the new seasonal menu.’,                          ‘date’,    ‘6’, ‘#06b6d4’, ‘planned’, NULL, NULL, NULL),
(‘7’,  ‘u1’, ‘Text check-in with Emma’,             (CURRENT_DATE + INTERVAL ‘4 days’)::date,   ‘09:15’, ‘Orem, UT’,                                   ‘Quick morning check-in before work.’,                 ‘text’,    ‘2’, ‘#ef4444’, ‘planned’, NULL, NULL, NULL),
(‘18’, ‘u1’, ‘Ward social mixer’,                   (CURRENT_DATE + INTERVAL ‘4 days’)::date,   ‘19:00’, ‘Provo City Center, Provo, UT’,               ‘Meet new people and reconnect with friends.’,         ‘other’,   NULL, ‘#84cc16’, ‘planned’, NULL, NULL, NULL),
(‘8’,  ‘u1’, ‘Pickleball with David’,               (CURRENT_DATE + INTERVAL ‘5 days’)::date,   ‘17:45’, ‘Provo Recreation Center, Provo, UT’,         ‘Play doubles with two friends.’,                      ‘hangout’, ‘1’, ‘#10b981’, ‘planned’, NULL, NULL, NULL),
(‘9’,  ‘u1’, ‘Coffee with Sophia’,                  (CURRENT_DATE + INTERVAL ‘6 days’)::date,   ‘08:30’, ‘Peace on Earth Coffee, Provo, UT’,           ‘Morning coffee before classes.’,                      ‘date’,    ‘4’, ‘#eab308’, ‘planned’, NULL, NULL, NULL),
(‘10’, ‘u1’, ‘Lunch with Ethan’,                    (CURRENT_DATE + INTERVAL ‘7 days’)::date,   ‘12:00’, ‘Cubby’’s, Orem, UT’,                         ‘Discuss internship updates.’,                         ‘hangout’, ‘5’, ‘#14b8a6’, ‘planned’, NULL, NULL, NULL),
(‘19’, ‘u1’, ‘Career fair prep’,                    (CURRENT_DATE + INTERVAL ‘7 days’)::date,   ‘18:30’, ‘UVU Library, Orem, UT’,                      ‘Resume review and mock interview prep.’,              ‘other’,   NULL, ‘#f59e0b’, ‘planned’, NULL, NULL, NULL),
(‘11’, ‘u1’, ‘Sunset walk with Olivia’,             (CURRENT_DATE + INTERVAL ‘8 days’)::date,   ‘19:15’, ‘Utah Lake Shore Trail, Provo, UT’,           ‘Light walk and talk.’,                                ‘date’,    ‘6’, ‘#6366f1’, ‘planned’, NULL, NULL, NULL),
(‘12’, ‘u1’, ‘Board game night with Noah’,          (CURRENT_DATE + INTERVAL ‘9 days’)::date,   ‘20:00’, ‘The Soap Factory, Provo, UT’,                ‘Friendly game night.’,                                ‘hangout’, ‘3’, ‘#a855f7’, ‘planned’, NULL, NULL, NULL),
(‘13’, ‘u1’, ‘Brunch with Emma’,                    (CURRENT_DATE + INTERVAL ‘10 days’)::date,  ‘11:00’, ‘Black Sheep Cafe, Provo, UT’,                ‘Catch up over brunch downtown.’,                      ‘date’,    ‘2’, ‘#fb7185’, ‘planned’, NULL, NULL, NULL),
(‘20’, ‘u1’, ‘Temple square road-trip planning’,    (CURRENT_DATE + INTERVAL ‘11 days’)::date,  ‘20:15’, ‘Pleasant Grove, UT’,                         ‘Coordinate rides and timing with group chat.’,        ‘other’,   NULL, ‘#22d3ee’, ‘planned’, NULL, NULL, NULL),
(‘14’, ‘u1’, ‘Text Noah to confirm gym time’,       (CURRENT_DATE + INTERVAL ‘12 days’)::date,  ‘16:10’, ‘Lehi, UT’,                                   ‘Confirm next week training block.’,                   ‘text’,    ‘3’, ‘#0ea5e9’, ‘planned’, NULL, NULL, NULL),
(‘15’, ‘u1’, ‘Date night with Olivia’,              (CURRENT_DATE + INTERVAL ‘14 days’)::date,  ‘19:45’, ‘Sol Agave, American Fork, UT’,               ‘Dinner reservation for two.’,                         ‘date’,    ‘6’, ‘#f43f5e’, ‘planned’, NULL, NULL, NULL);

-- =============================================================================
-- Goals (all belong to u1)
-- Demonstrates both goal types:
--   ‘measurable’ - has a numeric target and current value; history array shows
--                  progress snapshots used to render the progress chart.
--   ‘completion’  - binary done/not-done; target and current default to 0.
-- History entries: [{ "date": "YYYY-MM-DD", "value": number }, ...]
-- =============================================================================
INSERT INTO goals (id, user_id, title, goal_type, measure, actions, target_date, notes, category, target, current, completed, history) VALUES
-- Love: track intentional dates as a measurable goal
(‘1’, ‘u1’, ‘Go on 12 intentional dates’, ‘measurable’, ‘Dates completed’, ‘Plan one quality date per week’, (CURRENT_DATE + INTERVAL ‘120 days’)::date, ‘’, ‘love’, 12, 5, false, ‘[{"date":"2026-03-01","value":2},{"date":"2026-03-10","value":3},{"date":"2026-03-20","value":4},{"date":"2026-03-28","value":5}]’),
-- Fitness: workout frequency goal with running history
(‘2’, ‘u1’, ‘Gym consistency’, ‘measurable’, ‘Workouts completed’, ‘Lift 4x/week and track cardio’, (CURRENT_DATE + INTERVAL ‘90 days’)::date, ‘’, ‘fitness’, 40, 14, false, ‘[{"date":"2026-03-04","value":6},{"date":"2026-03-12","value":9},{"date":"2026-03-20","value":12},{"date":"2026-03-28","value":14}]’),
-- School: study session count goal
(‘3’, ‘u1’, ‘Finish semester strong’, ‘measurable’, ‘Study sessions’, ‘Complete at least 5 focused sessions per week’, (CURRENT_DATE + INTERVAL ‘75 days’)::date, ‘’, ‘school’, 50, 18, false, ‘[{"date":"2026-03-08","value":8},{"date":"2026-03-16","value":12},{"date":"2026-03-24","value":16},{"date":"2026-03-29","value":18}]’),
-- Work: completion-type goal (no numeric measure, just done/not done)
(‘4’, ‘u1’, ‘Secure summer internship’, ‘completion’, ‘’, ‘Apply weekly and follow up within 48 hours’, (CURRENT_DATE + INTERVAL ‘60 days’)::date, ‘’, ‘work’, 0, 0, false, ‘[]’),
-- Social: expand network with measurable connection count
(‘5’, ‘u1’, ‘Grow friend network’, ‘measurable’, ‘New meaningful connections’, ‘Attend two community/social events each month’, (CURRENT_DATE + INTERVAL ‘120 days’)::date, ‘’, ‘social’, 20, 7, false, ‘[{"date":"2026-03-05","value":3},{"date":"2026-03-15","value":5},{"date":"2026-03-29","value":7}]’);
